{{- include "library.workload" . }}

{{- if .Values.autoscaler.enabled }}{{ include "library.horizontalpodautoscaler" . }}{{- end }}

{{- if .Values.serviceaccount.enabled }}{{ include "library.rbac.serviceaccount" . }}{{ end }}

{{- if .Values.service.enabled }}{{ include "library.service" . }}{{ end }}

{{- if eq .Values.kind "StatefulSet" }}
{{- $root := deepCopy . }}
{{- $_ := set $root.Values.service "type" "Headless" }}
{{- $_ = set $root.Values.service "resource_name_suffix" "headless" }}
{{ include "library.service" $root }}
{{- end }}

{{- if .Values.kongingress.enabled }}
{{- include "library.kong.kongingress" . }}
{{- $_ := set .Values.ingress.annotations "konghq.com/override" .Release.Name }}
{{ end }}

{{- if .Values.ingress.enabled }}{{ include "library.ingress" . }}{{ end }}

{{- define "library.container_extras" }}
{{- if .service.liveness_probe }}
livenessProbe:
  {{- include "library.service.http_probe" .service | indent 2 }}
{{- end }}
{{- if .service.readiness_probe }}
readinessProbe:
  {{- include "library.service.http_probe" .service | indent 2 }}
{{- end }}
{{- end }}