{{- if kindIs "map" .Values.autoscaler }}
{{- include "k8s.autoscaling.horizontalPodAutoscaler" (set (deepCopy .) "Values" (set .Values.autoscaler "libk8s" .Values.libk8s)) }}
{{- end }}


{{- if kindIs "map" .Values.serviceAccount }}
{{- include "k8s.core.serviceAccount" (set (deepCopy .) "Values" (set .Values.serviceAccount "libk8s" .Values.libk8s)) }}
{{- include "k8s.factory.rbacRoles" . }}
{{- include "k8s.factory.rbackBindings" . }}
{{- end }}


{{- if kindIs "map" .Values.service }}
{{- include "k8s.core.service" (set (deepCopy .) "Values" (set .Values.service "libk8s" .Values.libk8s)) }}
{{- end }}


{{- if kindIs "map" .Values.ingress }}
{{- include "k8s.contextMutator.createIngressForService" . }}
{{- include "k8s.networking.ingress" (set (deepCopy .) "Values" .Values.ingress) }}
{{- end }}


{{- include "k8s.apps.workload" . }}