{{- include "library.workload" . }}

{{- if .Values.autoscaler.enabled }}{{ include "library.horizontalpodautoscaler" . }}{{- end }}

{{- if .Values.serviceaccount.enabled }}{{ include "library.rbac.serviceaccount" . }}{{ end }}

{{- if .Values.service.enabled }}{{ include "library.service" . }}{{ end }}

{{- if .Values.ingress.enabled }}{{ include "library.ingress" . }}{{ end }}

{{- if eq .Values.kind "StatefulSet" }}
{{- $root := deepCopy . }}
{{- $_ := set $root.Values.service "type" "Headless" }}
{{- $_ = set $root.Values.service "resource_name_suffix" "headless" }}
{{- $_ = unset $root.Values.service "annotations" }}
{{ include "library.service" $root }}
{{- end }}

