{{- define "k8s.core.service" }}
---
apiVersion: v1
kind: Service
{{- include "k8s.metadata" . }}
spec:
  {{- if .Values.headless }}
  clusterIP: None
  {{- else }}
  type: {{ coalesce .Values.type  .Values.libk8s.service.type }}
  {{- end }}
  {{- if .Values.externalName }}
  externalName: {{ .Values.externalName }}
  {{- end }}
  ports:
    {{- range .Values.ports }}
    - port: {{ .port }}
      {{- if .name }}
      name: {{ .name }}
      {{- end }}
      targetPort: {{ coalesce .targetPort .port }}
      protocol: {{ include "k8s.factory.serviceProtocol" . }}
    {{- end }}
  {{- if not .Values.externalName }}
  selector: {{ include "k8s.factory.podSelectorLabel" . | indent 4 }}
  {{- end }}
{{- end }}