### Application ########################

bots:
  ingress:
    enabled: true
    image: &image ghcr.io/ptonini/botman:latest
    command: ['/scripts/ingress-bot.sh']
  certificate:
    enabled: true
    image: *image
    command: ['/scripts/certificate-bot.sh']
  dns:
    enabled: true
    image: *image
    command: ['/scripts/dns-bot.sh']

### Deployment

nodeSelector: ~
env:
  DRY_RUN: "false"
  DEBUG: "false"
  INTERVAL: 1m
  AWS_REGION: us-east-1
  DNS_PROVIDER: aws
  CHARTS_REPOSITORY: https://example.com/helm-charts
  INGRESS_CHART: ingress
  CERTBOT_ACCOUNT: admin@example.com
  CERTBOT_MIN_LIFETIME: "30"
  CERTBOT_TEST_MODE: "false"
volumes:
  - name: scripts
    configMap:
      name: &configmap endpoint-scripts
      defaultMode: 0744
volumeMounts:
  - name: scripts
    mountPath: "/scripts"
    readOnly: true

configmap:
  resource_name: *configmap

serviceaccount:
  enabled: true
  roles:
    - scope: cluster
      rules:
        - apiGroups:
            - ""
          resources:
            - namespaces
            - configmaps
            - services
            - secrets
          verbs:
            - list
            - get
            - create
            - update
            - delete
            - patch
        - apiGroups:
            - extensions
            - networking.k8s.io
            - configuration.konghq.com
          resources:
            - ingresses
            - kongingresses
          verbs:
            - list
            - get
            - create
            - delete
            - patch
  bindings:
    - scope: cluster
      kind: ClusterRole