version: 7.10.2

certificate:
  enabled: false
  secretName: ~

http:
  tlsCertificate: ~
  service:
    annotations: ~
    type: LoadBalancer
    
elasticsearch:
  http: {}
  config: {}
  plugins:
    - repository-s3
  node_sets:
    - name: data0001
      count: 3
      nodeSelector: ~
      config: {}
      resources:
        requests:
          memory: 2048Mi
        limit:
          memory: 2048Mi
      jvm_heap_memory: 1800m
      jvm_extra_options: ""
      tolerations:
#        - key: "key1"
#          operator: "Exists"
#          effect: "NoSchedule"
      storage:
        size: 128Gi
        class: default
      env: {}
      volumeMounts: ~
      volumes: ~

kibana:
  count: 1
  nodeSelector: ~
  tolerations:
  config: ~
  http: {}
  resources:
    requests:
      memory: 512Mi
    limit:
      memory: 512Mi

apm:
  count: 0
  nodeSelector: ~
  http: {}
  config:
    output:
      elasticsearch:
        ssl:
          verification_mode: certificate
  resources:
    requests:
      memory: 512Mi
    limit:
      memory: 512Mi