scopes:
  namespaced: namespaced
  cluster: cluster
workload:
  appKind: Deployment
job:
  completions: 1
  parallelism:  1
  restartPolicy: OnFailure
cronjob:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
pod:
  serviceAccountName: default
  selectorLabel: app
service:
  type: ClusterIP
  port:
    protocol: TCP
secret:
  type: Opaque
webhook:
  kind: MutatingWebhookConfiguration
  matchPolicy: Equivalent
  failurePolicy: Ignore
  namespaceSelector:
    operator: NotIn
    namespaces:
      - kube-system
      - kube-public
      - kube-node-lease
  path: /mutate