apiVersion: v2
name: chartmuseum
description: Chartmuseum Helm Repository
type: application
version: 1.0.5
dependencies:
  - name: lib-default
    version: 1.0.2
    repository: https://ptonini.github.io/helm-charts
  - name: lib-kong
    version: 1.0.0
    repository: https://ptonini.github.io/helm-charts
