{{- include "library.deployment" . }}

{{- if .Values.serviceaccount.enabled }}
{{- include "library.rbac.serviceaccount" . }}
{{- end }}

{{- if .Values.service.enabled }}
{{- include "library.service" . }}
{{- end }}

{{ if .Values.kongingress.enabled }}
{{- $_ := set .Values.kongingress "annotations" .Values.ingress.annotations }}
{{- include "library.kong.kongingress" . }}
{{- $_ = set .Values.ingress.annotations "konghq.com/override" .Release.Name }}
{{ end }}

{{- if .Values.ingress.enabled }}
{{- include "library.ingress" . }}
{{- end }}
