{{- $_ := set .Values.annotations "kubernetes.io/ingress.class" .Values.ingress_class }}
{{ $root := dict "Chart" .Chart "Release" .Release "Values" (mergeOverwrite (deepCopy .Values) (coalesce .Values.kongconsumer dict)) }}
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
{{- include "library.metadata" . }}
username: {{ $.Values.username }}
credentials:
  - {{ include "library.factory.metadata.name" $root }}


{{- if .Values.password }}
{{- $root := deepCopy $ }}
{{- $_ = unset .Values.annotations "kubernetes.io/ingress.class" }}
{{- $_ = set .Values "plain_text" (dict "kongCredType" .Values.cred_type "username" .Values.username  "password" .Values.password ) }}
{{- include "library.secret" . }}
{{- end }}