{{- $_ := set .Values.certificate "dnsNames" (list (printf "%s.%s.svc" (include "k8s.factory.resourceName" .) (include "k8s.factory.resourceNamespace" .)))  }}
{{- include "k8s.certManager.certificate" (set (deepCopy .) "Values" (set .Values.certificate "libk8s" .Values.libk8s)) }}

{{- $_ = set .Values.webhook.annotations "cert-manager.io/inject-ca-from" (printf "%s/%s" .Release.Namespace .Release.Name) }}
{{- include "k8s.admissionRegistration.webhook" (set (deepCopy .) "Values" (set .Values.webhook "libk8s" .Values.libk8s)) }}

{{- include "k8s.core.serviceAccount" (set (deepCopy .) "Values" (set .Values.serviceAccount "libk8s" .Values.libk8s)) }}
{{- include "k8s.factory.rbacRoles" . }}
{{- include "k8s.factory.rbackBindings" . }}

{{- include "k8s.core.service" (set (deepCopy .) "Values" (set .Values.service "libk8s" .Values.libk8s)) }}

{{- include "k8s.apps.workload" . }}