replicas: 1

nodeSelector:
  - key: nodePoolClass
    operator: In
    values:
      - general

service:
  type: NodePort
  annotations: {}

tls:
#  secretName: rabbitmq-certificate
#  disableNonTLSListeners: false

tolerations:
#  - key: "key1"
#    operator: "Exists"
#    effect: "NoSchedule"

persistence:
  storageClassName: default
  storage: 3Gi

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 1Gi
  
envConfig: ~

additionalPlugins:
  - rabbitmq_top
  - rabbitmq_shovel
  - rabbitmq_shovel_management
  - rabbitmq_prometheus
  
additionalConfig: ""

secretBackend: ~

override: ~