{{- include "k8s.core.serviceAccount" . }}

{{- range .Values.roles }}
{{- include "k8s.rbac.role" (dict "Chart" $.Chart "Release" $.Release "Values" (set . "libk8s" $.Values.libk8s)) }}
{{- end }}

{{- range .Values.bindings }}
{{- include "k8s.rbac.binding" (dict "Chart" $.Chart "Release" $.Release "Values" (set . "libk8s" $.Values.libk8s)) }}
{{- end }}