{{- define "library.app" }}
---
apiVersion: apps/v1
kind: {{ coalesce .Values.kind "Deployment" }}
{{- include "library.metadata" . }}
spec:
  {{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.serviceName }}
  serviceName: {{ .Values.serviceName }}
  {{- end }}
  {{- if .Values.volumeClaimTemplates }}
  volumeClaimTemplates: {{ .Values.volumeClaimTemplates | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{ include "library.factory.podSelectorLabel" . | indent 6 }}
  template: {{ include "library.pod" . | indent 4 }}
{{- end }}


{{- define "library.horizontalpodautoscaler.metric" }}
- type: Resource
  resource:
    name: {{ .name }}
    target:
      type: {{ coalesce .type "Utilization" }}
      averageUtilization: {{ .averageUtilization }}
{{- end }}


{{- define "library.horizontalpodautoscaler" }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
{{- include "library.metadata" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ coalesce .Values.kind "Deployment" }}
    name: {{ include "library.factory.resource_name" . }}
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ if gt .Values.replicas .Values.autoscaler.maxReplicas }}{{ .Values.replicas }}{{ else }}{{ .Values.autoscaler.maxReplicas }}{{ end }}
  metrics:
    {{- range .Values.autoscaler.metrics }}
    {{ include "library.horizontalpodautoscaler.metric" . | indent 4 }}
    {{- end }}
{{- end }}