{{- define "library.app" }}
---
apiVersion: apps/v1
kind: {{ coalesce .Values.kind "Deployment" }}
{{- include "library.metadata" . }}
spec:
  {{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.serviceName }}
  serviceName: {{ .Values.serviceName }}
  {{- end }}
  {{- if .Values.volumeClaimTemplates }}
  volumeClaimTemplates: {{ .Values.volumeClaimTemplates | toYaml | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{ include "library.factory.podSelectorLabel" . | indent 6 }}
  template: {{ include "library.pod" . | indent 4 }}
{{- end }}


{{- define "library.horizontalpodautoscaler" }}
{{- $_ := set .Values.autoscaler "averageCpu" (coalesce .Values.autoscaler.averageCpu .Values.autoscaler.avr_cpu) }}
{{- $_ = set .Values.autoscaler "averageMemory" (coalesce .Values.autoscaler.averageMemory .Values.autoscaler.avr_cpu) }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
{{- include "library.metadata" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ coalesce .Values.kind "Deployment" }}
    name: {{ include "library.factory.resource_name" . }}
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ if gt .Values.replicas .Values.autoscaler.maxReplicas }}{{ .Values.replicas }}{{ else }}{{ .Values.autoscaler.maxReplicas }}{{ end }}
  metrics: {{ if .Values.autoscaler.metrics }}{{ .Values.autoscaler.metrics | toYaml | nindent 4 }}{{ end }}
    {{- if .Values.autoscaler.averageCpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.averageCpu }}
    {{- end }}
    {{- if .Values.autoscaler.averageMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaler.averageMemory }}
    {{- end }}
{{- end }}