{{- define "library.job.spec" }}
{{- if .Values.parallelism }}
parallelism: {{ .Values.parallelism }}
{{- end }}
{{- if .Values.completions }}
completions: {{ .Values.completions }}
{{- end }}
{{- if .Values.activeDeadlineSeconds }}
activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
{{- end }}
template: {{ include "library.pod" . | indent 2 }}
{{- end }}


{{- define "library.job" }}
---
apiVersion: batch/v1
kind: Job
{{- include "library.metadata" . }}
spec: {{ include "library.job.spec" . | indent 2 }}
{{- end }}


{{- define "library.cronjob" }}
---
apiVersion: batch/v1
kind: CronJob
{{- include "library.metadata" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec: {{ include "library.job.spec" . | indent 6 }}
{{- end }}