{{- define "library.configmap.data" }}
{{- include "library.factory.kv_list" .Values.data }}
{{- end }}

{{- define "library.configmap"}}
{{ $root := dict "Chart" .Chart "Release" .Release "Values" (mergeOverwrite (deepCopy .Values) (coalesce .Values.configmap dict)) }}
---
apiVersion: v1
kind: ConfigMap
{{- include "library.metadata" $root }}
data: {{- include "library.configmap.data" $root | indent 2}}
{{- end }}


{{- define "library.secret.data"}}
{{- range $k, $v := .Values.plain_text }}
  {{- if $v}}
{{ $k | quote }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- range $k, $v := .Values.encoded }}
  {{- if $v }}
{{ $k | quote }}: {{ $v }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "library.secret"}}
{{ $root := dict "Chart" .Chart "Release" .Release "Values" (mergeOverwrite (deepCopy .Values) (coalesce .Values.secret dict)) }}
---
apiVersion: v1
kind: Secret
{{- include "library.metadata" . }}
type: {{ .Values.type }}
data:
  {{- include "library.secret.data" . | indent 2 }}
{{- end }}