{{- define "library.container.extras" }}{{- end }}


{{- define "library.container" }}
{{- if kindIs "string" .image }}
image: {{ .image }}
{{- else if kindIs "map" .image }}
image: {{ if .image.registry }}{{ .image.registry }}/{{ end }}{{ .image.repository }}{{ if .image.tag }}:{{ .image.tag }}{{ else if .image.digest }}@{{ .image.digest }}{{ end }}
{{- end }}
{{- if .containerSecurityContext }}
securityContext: {{ .containerSecurityContext | toYaml | nindent 4 }}
{{- end }}
{{- if .imagePullPolicy }}
imagePullPolicy: {{ .imagePullPolicy }}
{{- end }}
{{- if .command }}
command: {{ .command | toYaml | nindent 2 }}
{{- end }}
{{- if .args }}
args: {{ .args | toYaml | nindent 2 }}
{{- end }}
{{- if .resources }}
resources: {{ .resources | toYaml | nindent 2 }}
{{- end }}
{{- if .volumeMounts }}
volumeMounts: {{ .volumeMounts | toYaml | nindent 2  }}
{{- end }}
{{- if .env }}
env:
{{- range $k, $v := .env }}
  {{- if $v}}
  - name: {{ $k }}
    {{- if kindIs "map" $v }}
    {{- $v | toYaml | nindent 4 }}
    {{- else }}
    value: {{ $v | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- if or .envSecrets .envConfigmaps  }}
envFrom:
  {{- range .envConfigmaps }}
  - configMapRef:
      name: {{ . }}
  {{- end }}
  {{- range .envSecrets }}
  - secretRef:
      name: {{ . }}
  {{- end }}
{{- end }}
{{- if ((.service).enabled) }}
  {{- if .service.port }}
  {{- $_ := set .service "ports" (append (default list .service.ports) (dict "port" .service.port) )}}
  {{- end }}
ports:
  {{- range .service.ports }}
  - containerPort: {{ coalesce .targetPort .port }}
    protocol: {{ include "library.factory.service.port.protocol" . }}
  {{- end }}
{{- end }}
{{- if .readinessProbe }}
readinessProbe: {{ .readinessProbe | toYaml | nindent 2}}
{{- end }}
{{- if .livenessProbe }}
livenessProbe: {{ .livenessProbe | toYaml | nindent 2}}
{{- end }}
{{- if .lifecycle }}
lifecycle: {{ .lifecycle | toYaml | nindent 2}}
{{- end }}
{{- include "library.container.extras" . }}
{{- end }}