{{- define "library.cronjob" }}
---
apiVersion: batch/v1beta1
kind: CronJob
{{- include "library.metadata" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  jobTemplate:
    spec:
      {{- if .Values.parallelism }}
      parallelism: {{ .Values.parallelism }}
      {{- end }}
      {{- if .Values.completions }}
      completions: {{ .Values.completions }}
      {{- end }}
      {{- if .Values.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      {{- end }}
      template:
        {{- include "library.pod" . | indent 8 }}
{{- end }}