{{- define "library.factory.resource_name" }}
{{- coalesce .Values.resource_name .Release.Name }}{{ if .Values.resource_name_suffix }}-{{ .Values.resource_name_suffix }}{{ end }}
{{- end}}


{{- define "library.factory.service.port.name" }}
{{- coalesce .name  "http"}}
{{- end }}


{{- define "library.factory.service.port.protocol" }}
{{- coalesce .protocol  "TCP" }}
{{- end }}


{{- define "library.factory.kv_list" }}
{{- range $k, $v := . }}
{{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}


{{- define "library.factory.pod.labels" }}
{{- if ((.Values.pod).labels) }}
{{- include "library.factory.kv_list" .Values.pod.labels }}
{{- else }}
app: {{ .Release.Name }}
{{- end }}
{{- end }}