{{- define "library.factory.resource_name" }}
{{- coalesce .Values.resource_name .Release.Name }}{{ if .Values.resource_name_suffix }}-{{ .Values.resource_name_suffix }}{{ end }}
{{- end}}


{{- define "library.factory.service.port.protocol" }}
{{- coalesce .protocol  "TCP" }}
{{- end }}


{{- define "library.factory.kv_list" }}
{{- range $k, $v := . }}
{{ $k }}: {{ if $v }}{{ $v | quote }}{{ else }}"{{ $v }}"{{ end }}
{{- end }}
{{- end }}


{{- define "library.factory.podSelectorLabel" }}
{{ coalesce ((.Values).podSelectorLabel).key "app" }}: {{ coalesce ((.Values).podSelectorLabel).value .Values.resource_name .Release.Name }}
{{- end }}