{{- define "library.metadata" }}
metadata:
  name: {{ include "library.factory.metadata.name" . }}
  {{- if ne (.Values.scope | toString) "cluster" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- include "library.metadata.annotations" . | indent 2 }}
  {{- if .Values.labels }}
  labels:
    {{- include "library.factory.kv_list" .Values.labels | indent 4 }}
  {{- end }}
{{- end }}


{{- define "library.metadata.annotations" }}
annotations:
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/name: {{ .Release.Name }}
  helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  {{- include "library.factory.kv_list" .Values.annotations | indent 2 }}
{{- end }}