{{- define "library.pod.template" }}
metadata:
  {{- if ((.Values.pod).annotations) }}
  annotations:
    {{- include "library.factory.kv_list" .Values.pod.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "library.factory.pod.labels" . | indent 4 }}
spec:
  {{- if .Values.securityContext }}
  securityContext:{{ .Values.securityContext | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.nodeSelector }}
  nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets: {{- .Values.imagePullSecrets | toYaml | nindent 4}}
  {{- end }}
  {{- if .Values.restartPolicy }}
  restartPolicy: {{ .Values.restartPolicy }}
  {{- end }}
  {{- if or .Values.volumes .Values.token_volume }}
  volumes:
    {{- if .Values.volumes }}
    {{- .Values.volumes | toYaml | nindent 4 }}
    {{- end }}
    {{- if ((.Values.token_volume).enabled) }}
    {{- include "library.volume.token_projection" .Values.token_volume | indent 4 }}
    {{- include "library.volume.extras" . | indent 4 }}
    {{- end }}
  {{- end }}
  {{- if ((.Values.serviceaccount).enabled) }}
  serviceAccountName: {{ include "library.factory.pod.serviceaccountname" . }}
  {{- end }}
  {{- if .Values.initContainers }}
  initContainers:
    {{- range .Values.initContainers }}
    - name: {{ .name }}
      {{- include "library.container" . | indent 6 }}
    {{- end }}
  {{- end }}
  containers:
  {{- if .Values.containers }}
    {{- range .Values.containers }}
    - name: {{ $.Release.Name }}-{{ . }}
      {{- include "library.container" (get $.Values .) | indent 6 }}
    {{- end }}
  {{- else }}
    - name: {{ .Release.Name }}
      {{- include "library.container" .Values | indent 6 }}
  {{- end }}
  {{- end }}


{{- define "library.volume.token_projection" }}
- name: {{ .name }}
  projected:
    sources:
      - serviceAccountToken:
          path: {{ .name }}
          {{- if .expiration }}
          expirationSeconds: {{ .expiration }}
          {{- end }}
          {{- if .audience }}
          audience: {{ .audience }}
          {{- end }}
{{- end }}

{{- define "library.volume.extras" }}{{- end }}