{{- define "library.pod" }}
{{- $containers := list }}
{{- if hasKey .Values "image" }}
  {{- $container := deepCopy .Values }}
  {{- $_ := set $container "name" .Release.Name }}
  {{- $containers = append $containers $container }}
{{- end }}
{{- range (list .Values.containers .Values.extraContainers) }}
  {{- if kindIs "slice" . }}
    {{- $containers = concat $containers . }}
  {{- else if kindIs "map" . }}
    {{- range $k, $v := . }}
      {{- $containers = append $containers (set $v "name" $k) }}
    {{- end }}
  {{- end }}
{{- end }}
metadata:
  {{- if ((.Values.pod).annotations) }}
  annotations: {{ include "library.factory.kv_list" .Values.pod.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "library.factory.podSelectorLabel" . | indent 4 }}
    {{- if ((.Values.pod).labels) }}
    {{- include "library.factory.kv_list" .Values.pod.labels | indent 4 }}
    {{- end }}
spec:
  {{- include "library.pod.spec" (mergeOverwrite .Values (coalesce ((.Values.pod).spec) dict)) | indent 2 }}
  {{- if ((.Values.serviceaccount).enabled) }}
  serviceAccountName: {{ coalesce .Values.serviceaccount.resource_name .Release.Name }}
  {{- else if .Values.serviceAccountName }}
  serviceAccountName: {{ .Values.serviceAccountName }}
  {{- end }}
  {{- if .Values.initContainers }}
  initContainers:
    {{- range .Values.initContainers }}
    {{- include "library.container" . | indent 2 }}
    {{- end }}
  {{- end }}
  containers:
    {{- range $containers }}
    {{- include "library.container" . | indent 4 }}
    {{- end }}
{{- end }}


{{- define "library.pod.spec" }}
{{- if .terminationGracePeriodSeconds }}
terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
{{- end }}
{{- if .hostNetwork }}
hostNetwork: {{ .hostNetwork }}
{{- end }}
{{- if .hostPID }}
hostPID: {{ .hostPID }}
{{- end }}
{{- if .dnsPolicy }}
dnsPolicy: {{ .dnsPolicy }}
{{- end }}
{{- if .securityContext }}
securityContext:{{ .securityContext | toYaml | nindent 2 }}
{{- end }}
{{- if .nodeSelector }}
nodeSelector: {{ .nodeSelector | toYaml | nindent 2 }}
{{- end }}
{{- if .imagePullSecrets }}
imagePullSecrets:
  {{- range .imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- if .restartPolicy }}
restartPolicy: {{ .restartPolicy }}
{{- end }}
{{- if .tolerations }}
tolerations: {{ .tolerations | toYaml | nindent 2 }}
{{- end }}
{{- if or .volumes .token_volume }}
volumes: {{ if .volumes }}{{ .volumes | toYaml | nindent 2 }}{{ end }}
  {{- if ((.token_volume).enabled) }}
  {{- include "library.volume.token_projection" .token_volume }}
  {{- end }}
{{- end }}
{{- end }}


{{- define "library.volume.token_projection" }}
  - name: {{ .name }}
    projected:
      sources:
        - serviceAccountToken:
            path: {{ .name }}
          {{- if .expiration }}
            expirationSeconds: {{ .expiration }}
          {{- end }}
          {{- if .audience }}
            audience: {{ .audience }}
          {{- end }}
{{- end }}