{{- define "library.rbac.binding" }}
{{- $kind := ternary "ClusterRoleBinding" "RoleBinding" (eq (toString .Values.scope) "cluster") }}
{{- $_ := set .Values "resource_name" .Values.roleName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kind }}
{{- include "library.metadata" . }}
roleRef:
  kind: {{ .Values.roleKind }}
  name: {{ .Values.roleName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.serviceAccount.namespace }}
{{- end }}


{{- define "library.rbac.role" }}
{{- $kind := ternary "ClusterRole" "Role" (eq (toString .Values.scope) "cluster") }}
{{- $bindingValues := dict "scope" .Values.scope "roleKind" $kind "roleName" (include "library.factory.resource_name" .) "serviceAccount" .Values.serviceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kind }}
{{- include "library.metadata" . }}
rules: {{ .Values.rules | toYaml | nindent 2 }}

{{- if (and .Values.serviceAccount (default true .Values.createBinding)) }}
  {{- include "library.rbac.binding" (dict "Chart" .Chart "Release" .Release "Values" $bindingValues) }}
{{- end }}
{{- if (hasKey .Values "bindings") }}
  {{- range .Values.bindings }}
    {{- include "library.rbac.binding" (dict "Chart" $.Chart "Release" $.Release "Values" (mergeOverwrite $bindingValues .)) }}
  {{- end }}
{{- end }}
{{- end }}


{{- define "library.rbac.serviceaccount" }}
{{- $root := dict "Chart" .Chart "Release" .Release "Values" (mergeOverwrite (deepCopy .Values) (coalesce .Values.serviceaccount dict)) }}
---
apiVersion: v1
kind: ServiceAccount
{{- include "library.metadata" $root }}

{{- range $root.Values.roles }}
  {{- $role := dict "Chart" $root.Chart "Release" $root.Release "Values" . }}
  {{- $_ := set $role.Values "serviceAccount" (dict "name" (include "library.factory.resource_name" $root) "namespace" $root.Release.Namespace) }}
  {{- include "library.rbac.role" $role }}
{{- end }}
{{- end }}