{{- define "library.rbac.role" }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq (toString .Values.scope) "cluster" }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
{{- include "library.metadata" . }}
rules: {{ .Values.rules | toYaml | nindent 2 }}
{{- end }}


{{- define "library.rbac.binding" }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq .Values.scope "cluster" }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
{{- include "library.metadata" . }}
roleRef:
  kind: {{ .Values.kind }}
  name: {{ coalesce .Values.name .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end }}


{{- define "library.rbac.serviceaccount" }}
---
apiVersion: v1
kind: ServiceAccount
{{- include "library.metadata" . }}

{{- range ternary (.Values.serviceaccount).roles .Values.roles (hasKey .Values "serviceaccount" ) }}
{{- $role := deepCopy $ }}
{{- $_ := set $role "Values" . }}
{{- include "library.rbac.role" $role }}
{{- end }}

{{- range ternary (.Values.serviceaccount).bindings .Values.bindings (hasKey .Values "serviceaccount" ) }}
{{- $binding := deepCopy $ }}
{{- $_ := set $binding "Values" . }}
{{- include "library.rbac.binding" $binding }}
{{- end }}

{{- end }}