{{- define "library.secret"}}
{{- $root := deepCopy . }}
{{- if .Values.secret }}
{{- $values := merge $root.Values .Values.secret }}
{{- $_ := set $root "Values" $values }}
{{- end }}
---
apiVersion: v1
kind: Secret
{{- include "library.metadata" . }}
type: {{ .Values.type }}
data:
  {{- include "library.secret.data" . | indent 2 }}
{{- end }}


{{- define "library.secret.data"}}
{{- range $k, $v := .Values.plain_text }}
  {{- if $v}}
{{ $k | quote }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
{{- range $k, $v := .Values.encoded }}
  {{- if $v }}
{{ $k | quote }}: {{ $v }}
  {{- end }}
{{- end }}
{{- end }}