{{- define "library.service" }}
{{ $root := dict "Chart" .Chart "Release" .Release "Values" (mergeOverwrite (deepCopy .Values) (coalesce .Values.service dict)) }}

{{- if $root.port }}
{{- $_ := set $root "ports" (append (default list $root.ports) (dict "port" $root.port) )}}
{{- end }}
---
apiVersion: v1
kind: Service
{{- include "library.metadata" $root }}
spec:
  {{- if eq $root.Values.type "Headless" }}
  clusterIP: None
  {{- else }}
  type: {{ coalesce $root.Values.type  "NodePort" }}
  {{- end }}
  ports:
    {{- range $root.Values.ports }}
    - name: {{ include "library.factory.service.port.name" . }}
      port: {{ .port }}
      targetPort: {{ coalesce .targetPort .port }}
      protocol: {{ include "library.factory.service.port.protocol" . }}
    {{- end }}
  selector:
    {{- include "library.factory.pod.labels" $root  | indent 4 }}
{{- end}}


{{- define "library.service.http_probe" }}
{{- include "library.container.http_probe" (dict "path" .monitoring.route "port" .port "timeout_seconds" "35") }}
{{- end }}
