{{- define "library.service" }}
{{- $root := dict "Chart" .Chart "Release" .Release "Values" (mergeOverwrite (deepCopy .Values) (coalesce .Values.service dict)) }}
{{- if $root.Values.port }}
{{- $_ := set $root.Values "ports" (append (default list $root.Values.ports) (dict "port" $root.Values.port) )}}
{{- end }}
---
apiVersion: v1
kind: Service
{{- include "library.metadata" $root }}
spec:
  {{- if eq $root.Values.type "Headless" }}
  clusterIP: None
  {{- else }}
  type: {{ coalesce $root.Values.type  "NodePort" }}
  {{- end }}
  {{- if eq $root.Values.type "ExternalName" }}
  externalName: {{ $root.Values.externalName }}
  {{- end }}
  ports:
    {{- range $root.Values.ports }}
    - name: {{ coalesce .name  "http" }}
      port: {{ .port }}
      targetPort: {{ coalesce .targetPort .port }}
      protocol: {{ include "library.factory.service.port.protocol" . }}
    {{- end }}
  {{- if ne $root.Values.type "ExternalName" }}
  selector: {{- include "library.factory.pod.labels" $root  | indent 4 }}
  {{- end }}
{{- end}}