{{- define "library.workload" }}
---
apiVersion: {{ coalesce .Values.apiVersion "apps/v1" }}
kind: {{ coalesce .Values.kind "Deployment" }}
{{- include "library.metadata" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "library.factory.pod.labels" . | indent 6 }}
  template:
    {{- include "library.pod.template" . | indent 4 }}
{{- end }}


{{- define "library.horizontalpodautoscaler" }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
{{- include "library.metadata" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "library.factory.metadata.name" . }}
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ if gt .Values.replicas .Values.autoscaler.maxReplicas }}{{ .Values.replicas }}{{ else }}{{ .Values.autoscaler.maxReplicas }}{{ end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaler.avr_cpu }}
{{- end }}