apiVersion: v2
name: psono
description: Psono
type: application
version: 1.0.3
dependencies:
  - name: lib-default
    version: 1.0.1
    repository: https://ptonini.github.io/helm-charts
  - name: lib-kong
    version: 1.0.0
    repository: https://ptonini.github.io/helm-charts
