### Application ######################

debug: false
allowed_domain: example.com.br
allow_registration: True
allow_lost_password: True
throttling: true
secret_key: ~
activation_link_secret: ~
db_secret: ~
email_secret_salt: ~
private_key: ~
public_key: ~
enforce_matching_username_and_email: True
redis:
  uri: ~
email:
  from: noreply@example.com.br
  host: ~
  host_user: ~
  host_password : ~
  port: 587
  subject_prefix: ~
postgresql:
  name: psono
  user: psono
  password: ~
  host: ~
  port: 5432


### Deployment ######################

nodeSelector: ~
annotations: {}
replicas: 3
volumes:
  - name: config
    configMap:
      defaultMode: 0644
      name: &configmap psono-config
image: psono/psono-server:latest
resources:
  requests:
    memory: 384Mi
readiness_http_probe:
  port: &server_port 8080
  path: &server_health /healthcheck/
volumeMounts:
  - name: config
    mountPath: /root/.psono_server/settings.yaml
    subPath: settings.yaml
    readOnly: true
env:
  UWSGI_PORT: *server_port

extraContainers:
  - name: client
    image: psono/psono-client:latest
    resources:
      requests:
        memory: 128Mi
    readiness_http_probe:
      port: &client_port 80
      path: &client_health /
    volumeMounts: &shared_mounts
      - name: config
        mountPath: /usr/share/nginx/html/config.json
        subPath: config.json
        readOnly: true

configmap:
  resource_name: *configmap

service:
  resource_name: &service_name psono
  ports:
    - name: server
      port: *server_port
    - name: client
      port: *client_port

kongingress:
  enabled: true

ingress:
  annotations: {}
  domain: psono.example.com.br
  paths:
    - service: *service_name
      port: *server_port
      path: /server
    - service: *service_name
      port: *client_port

admin:
  enabled: true
  replicas: 1
  resource_name: &admin_name psono-admin
  pod:
    labels:
      app: *admin_name
  image: psono/psono-admin-client:latest
  resources:
    requests:
      memory: 256Mi
  service:
    enabled: true
    port: &admin_port 80
  readiness_http_probe:
    port: *admin_port
    path: &admin_health /portal/login
  volumeMounts:
    *shared_mounts
