{{- range .Values.beats  }}
{{- with (dict "Chart" $.Chart "Release" $.Release "Values" (dict "global" $.Values.global "version" $.Values.version "beat" . ))}}
{{- $_ := set .Values "resource_name" (printf "%s-%s" .Release.Name .Values.beat.type)}}
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
{{- include "library.metadata" . }}
spec:
  type: {{ .Values.beat.type }}
  version: {{ .Values.version }}
  {{- if $.Values.elasticsearch.enabled }}
  elasticsearchRef:
    name: {{ .Release.Name }}
  {{- end }}
  {{- if $.Values.kibana.enabled }}
  kibanaRef:
    name: {{ .Release.Name }}
  {{- end}}
  config: {{ .Values.beat.config | toYaml | nindent 4 }}
  deployment:
    replicas: {{ default 1 .Values.beat.replicas }}
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
        {{- if .Values.beat.nodeSelector }}
        nodeSelector: {{ .Values.beat.nodeSelector | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.beat.tolerations }}
        tolerations: {{ .Values.beat.tolerations | toYaml | nindent 10 }}
        {{- end }}
        containers:
          - name: {{ .Values.beat.type }}
            {{- if .resources  }}
            resources: {{ .Values.beat.resources | toYaml | nindent 14 }}
            {{- end }}
{{- end }}
{{- end }}