{{- if .Values.kibana.enabled }}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
{{- include "library.metadata" . }}
spec:
  version: {{ .Values.version }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}
  {{- include "elasticsearch.http" (merge .Values.kibana.http (deepCopy .Values.global.http)) | indent 2 }}
  {{- if .Values.kibana.config }}
  config: {{ .Values.kibana.config | toYaml | nindent 4 }}
  {{- end }}
  podTemplate:
    spec:
      serviceAccountName: {{ $.Release.Name }}
      {{- if .Values.kibana.nodeSelector }}
      nodeSelector: {{ .Values.kibana.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.kibana.tolerations }}
      tolerations: {{ .Values.kibana.tolerations | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: kibana
          resources: {{ .Values.kibana.resources | toYaml | nindent 12 }}
{{- end }}

{{- if .Values.kibana.ingress.enabled }}
{{ $root := dict "Chart" .Chart "Release" .Release "Values" .Values.kibana }}
{{ $_ := set $root.Values.ingress "resource_name" (printf "%s-kb" .Release.Name) }}
{{ $_ = set $root.Values.ingress "paths" (list (dict "port" 5601 "service" (printf "%s-http" $root.Values.ingress.resource_name ))) }}
{{ $_ = set $root.Values.ingress "certificate" (printf "%s-ingress-tls" $root.Values.ingress.resource_name) }}
{{ include "library.ingress" (dict "Chart" .Chart "Release" .Release "Values" .Values.kibana) }}
{{- end }}