{{- include "library.workload" . }}

{{- include "library.service" . }}

{{- if .Values.kongingress.enabled }}
{{- include "library.kong.kongingress" . }}
{{- $_ := set .Values.ingress.annotations "konghq.com/override" .Release.Name }}
{{ end }}

{{- include "library.ingress" . }}

{{- if .Values.admin.enabled }}
{{- include "library.workload" (dict "Chart" .Chart "Release" .Release "Values" .Values.admin) }}
{{- include "library.service" (dict "Chart" .Chart "Release" .Release "Values" .Values.admin) }}
{{- end }}
