apiVersion: v2
name: admission-controller
description: Kubernetes Admission Controller
type: application
version: 1.6.0
dependencies:
  - name: lib-default
    version: 1.0.3
    repository: https://ptonini.github.io/helm-charts
