certificate:
  volume: certs
  mountPoint: certs
  secretName: ~
  certManager:
    enable: true
    issuer: self-signed
    issuerKind: ClusterIssuer

image: kac
livenessProbe: &livenessProbe
  httpGet:
    path: /health
    port: 8443
    scheme: HTTPS
  initialDelaySeconds: 3
readinessProbe: *livenessProbe
volumeMounts: []
volumes: []

webhook:
  annotations: {}
  kind: MutatingWebhookConfiguration
  failurePolicy: Ignore
  ignoredNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease
  rules: ~
  caBundle: ~
  path: /mutate
service:
  enabled: true
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443

serviceaccount:
  enabled: true