certificates:
  secret: ~
  volume: certs
  mountPoint: /certs

env:
  POD_NAMESPACE:
    valueFrom:
      fieldRef:
        fieldPath: "metadata.namespace"
livenessProbe: &livenessProbe
  httpGet:
    path: /health
    port: 8443
    scheme: HTTPS
  initialDelaySeconds: 3
readinessProbe: *livenessProbe
volumeMounts: []
volumes: []

webhook:
  kind: MutatingWebhookConfiguration
  failurePolicy: Ignore
  ignoredNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease
  rules: ~
  caBundle: ~
  path: /mutate
service:
  enabled: true
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443

serviceaccount:
  enabled: true