default_read: everyone
default_write: everyone
session:
  encrypt_key: ""
  validate_key: ""
  secure: false
auth:
  admin_hash: ~
  database: ~
  address: ~
storage:
  type: s3
  bucket: ~
  dir: ~
cache:
  database: ~
  address: ~
aws:
  role_arn: ~
  access_key: ~
  secret_key: ~
  

nodeSelector: ~
replicas: 1
pod:
  annotations: ~
securityContext:
  fsGroup: 1000
  runAsUser: 1000
imagePullSecrets: []
image: ghcr.io/ptonini/pypicloud:latest
args: ~
env:
  AWS_SDK_LOAD_CONFIG: "true"
resources:
  requests:
    memory: 512Mi
token_volume:
  enabled: true
  name: token
  expiration: 3600
  audience: ~
volumes:
  - name: config
    configMap:
      defaultMode: 0600
      name: &configmap pypicloud-config
volumeMounts:
  - name: config
    mountPath: /etc/pypicloud/config.ini
    subPath: config.ini
    readOnly: true
readiness_http_probe:
  path: &health_path /simple
  port: &port 8080
liveness_http_probe: ~

configmap:
  resource_name: *configmap

service:
  enabled: true
  port: *port
  monitoring:
    route: *health_path
    method: GET

kongingress:
  enabled: true
  route:
    protocols: [ "https" ]
    https_redirect_status_code: 302
    strip_path: true

ingress:
  enabled: true
  domain: pypi.example.com
  annotations: {}
  monitoring:
    route: *health_path

serviceaccount:
  enabled: true

