replicas: 1
token_volume:
  enabled: true
  name: token
  expiration: 3600
resources:
  requests:
    cpu: 50m
autoscaler:
  enabled: false
  max_replicas: 1
  avr_cpu: 80
serviceaccount:
  enabled: false
service:
  enabled: true
  port: 8080
  liveness_probe: false
  readiness_probe: false
  annotations: {}
  monitoring:
    route: /
    method: GET
kongingress:
  enabled: false
  annotations: {}
  route:
    protocols: [ "https" ]
    https_redirect_status_code: 302
    strip_path: true
ingress:
  enabled: false
  annotations: {}