kind: Deployment
replicas: ~
token_volume:
  enabled: true
  name: token
  expiration: 3600
autoscaler:
  enabled: false
serviceaccount:
  enabled: false
service:
  enabled: true
ingress:
  enabled: false
  annotations: {}
volumeClaimTemplates: []