ingressAnnotations:
  ingress.kubernetes.io/force-ssl-redirect: "true"
  konghq.com/strip-path: "true"

image: ghcr.io/ptonini/ingress-bot:0.1.0
env: {}

serviceAccount:
  bindings:
    - scope: cluster
  roles:
    - rules:
        - apiGroups:
            - ""
          resources:
            - services
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - networking.k8s.io
          resources:
            - ingresses
          verbs:
            - get
            - list
            - create
            - update
            - delete
      scope: cluster