{{- $_ := set .Values "volumes" (append .Values.volumes (dict "name" .Values.certificates.volume "secret" (dict "secretName" .Values.certificates.secret ))) }}
{{- $_ = set .Values "volumeMounts" (append .Values.volumeMounts (dict "name" .Values.certificates.volume "mountPath" .Values.certificates.mountPoint "readOnly" true)) }}

{{- include "library.webhook" . }}

{{- include "library.workload" . }}

{{ include "library.service" . }}

{{- if ((.Values.autoscaler).enabled) }}{{ include "library.horizontalpodautoscaler" . }}{{ end }}

{{- if .Values.serviceaccount.enabled }}{{ include "library.rbac.serviceaccount" . }}{{ end }}