{{- if .Values.apm.enabled }}
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
{{- include "library.metadata" . }}
spec:
  version: {{ .Values.version }}
  count: {{ .Values.apm.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}
  {{- include "elasticsearch.http" (merge (deepCopy .Values.http) .Values.apm.http) | indent 2 }}
  config: {{ .Values.apm.config | toYaml | nindent 4 }}
  podTemplate:
    spec:
      serviceAccountName: {{ .Release.Name }}
      {{- if .Values.apm.nodeSelector }}
      nodeSelector: {{ .Values.apm.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.apm.tolerations }}
      tolerations: {{ .Values.apm.tolerations | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: apm
          resources: {{ .Values.apm.resources | toYaml | nindent 10 }}
{{- end }}
