---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
{{- include "library.metadata" . }}
spec:
  version: {{ .Values.version }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Release.Name }}
  http:
    {{- include "elasticsearch.http" (merge (deepCopy .Values.http) .Values.kibana.http) | indent 4}}
  {{- if .Values.kibana.config }}
  config: {{ .Values.kibana.config | toYaml | nindent 4 }}
  {{- end }}
  podTemplate:
    spec:
      serviceAccountName: {{ $.Release.Name }}
      {{- if .Values.kibana.nodeSelector }}
      nodeSelector: {{ .Values.kibana.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.kibana.tolerations }}
      tolerations: {{ .Values.kibana.tolerations | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: kibana
          resources: {{ .Values.kibana.resources | toYaml | nindent 12 }}
