{{- $root := deepCopy . }}
{{- $_ := set $root.Values.configmap "data" dict }}
{{- $_ = set $root.Values "containers" dict }}

{{- range  $path, $_ := .Files.Glob "scripts/*.sh" }}
{{- $_ = set $root.Values.configmap.data ($path | base) ($.Files.Get $path) }}
{{- end }}

{{- range  $name, $values := .Values.bots }}
{{- if (get $values "enabled") }}
{{- $common := pick $.Values "image" "env" "volumeMounts" }}
{{- $_ = set $root.Values.containers $name (mergeOverwrite $common $values)}}
{{- end }}
{{- end }}
{{- $_ = unset $root.Values "image" }}

{{- include "library.workload" $root }}

{{- include "library.rbac.serviceaccount" $root }}

{{- include "library.configmap" $root }}
